[package]
name = "console-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = { workspace = true }
pbjson = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
pbjson-build = { workspace = true }
protoc-bin-vendored = { workspace = true }

[[test]]
name = "version_json_test"
path = "tests/version_json_test.rs"

[[test]]
name = "favorites_json_test"
path = "tests/favorites_json_test.rs"

[[test]]
name = "settings_json_test"
path = "tests/settings_json_test.rs"

[[test]]
name = "project_json_test"
path = "tests/project_json_test.rs"

[[test]]
name = "usage_json_test"
path = "tests/usage_json_test.rs"

[[test]]
name = "ports_json_test"
path = "tests/ports_json_test.rs"
