// swift-tools-version: 5.9
import PackageDescription

// Umbrella package exposing the three Codevisor libraries as a single local
// Swift package, so the app links one package reference. Each target reuses the
// per-module folder layout under Packages/<Module>/.
let package = Package(
    name: "CodevisorKit",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "ACPKit", targets: ["ACPKit"]),
        .library(name: "StreamMarkdown", targets: ["StreamMarkdown"]),
        .library(name: "CodevisorTheming", targets: ["CodevisorTheming"]),
        .library(name: "CodeHighlighter", targets: ["CodeHighlighter"]),
        .library(name: "CodevisorCore", targets: ["CodevisorCore"])
    ],
    dependencies: [],
    targets: [
        // MARK: CodevisorTheming (VSCode/Shiki theme parsing, normalization,
        // palette derivation — Foundation-only, no SwiftUI)
        .target(
            name: "CodevisorTheming",
            path: "CodevisorTheming/Sources/CodevisorTheming",
            resources: [.copy("Resources/Themes")]
        ),
        .testTarget(
            name: "CodevisorThemingTests",
            dependencies: ["CodevisorTheming"],
            path: "CodevisorTheming/Tests/CodevisorThemingTests"
        ),

        // MARK: ACPKit
        .target(
            name: "ACPKit",
            path: "ACPKit/Sources/ACPKit"
        ),
        .testTarget(
            name: "ACPKitTests",
            dependencies: ["ACPKit"],
            path: "ACPKit/Tests/ACPKitTests"
        ),

        // MARK: StreamMarkdown
        .target(
            name: "StreamMarkdown",
            path: "StreamMarkdown/Sources/StreamMarkdown"
        ),
        .testTarget(
            name: "StreamMarkdownTests",
            dependencies: ["StreamMarkdown"],
            path: "StreamMarkdown/Tests/StreamMarkdownTests"
        ),

        // MARK: CodeHighlighter (Shiki running in JavaScriptCore; the bundled
        // highlighter.js is generated by apps/macos/scripts/build-highlighter.mjs)
        .target(
            name: "CodeHighlighter",
            path: "CodeHighlighter/Sources/CodeHighlighter",
            resources: [.copy("Resources/highlighter.js")]
        ),
        .testTarget(
            name: "CodeHighlighterTests",
            dependencies: ["CodeHighlighter"],
            path: "CodeHighlighter/Tests/CodeHighlighterTests"
        ),

        // MARK: CodevisorCore (app logic: models, repositories, DI, view models)
        .target(
            name: "CodevisorCore",
            dependencies: [
                "ACPKit",
                "CodevisorTheming"
            ],
            path: "CodevisorCore/Sources/CodevisorCore"
        ),
        .testTarget(
            name: "CodevisorCoreTests",
            dependencies: ["CodevisorCore", "ACPKit"],
            path: "CodevisorCore/Tests/CodevisorCoreTests"
        )
    ]
)
