import type { z } from "zod";

/** Tool capability tier used for permission approval resolution */
export type ToolTier = "read" | "write" | "exec";

/** Security approval mode for controlling tool execution permissions */
export type ApprovalMode = "always-ask" | "accept-edits" | "plan-mode" | "full-access";

/** Permission resolution policy decision */
export type ApprovalPolicy = "allow" | "deny" | "prompt";

/** Permission request payload emitted when a tool call requires user approval */
export interface PermissionRequest {
  requestId: string;
  toolCallId: string;
  toolName: string;
  args: unknown;
  tier: ToolTier;
  reason?: string;
}

/**
 * Represents the AI model's request to execute a tool.
 */
export interface ToolCall {
  /**
   * A unique identifier for this specific tool call. This ID is used to
   * match the result back to the request.
   */
  id: string;
  /**
   * The name of the tool to be executed (e.g., "readFile", "searchWeb").
   */
  name: string;
  /**
   * The arguments for the tool, as provided by the model.
   * This is a raw object that needs to be parsed by the tool's input schema.
   */
  arguments: unknown;
}

/**
 * Represents the output of a tool's execution, to be sent back to the model.
 */
export interface ToolResult {
  /**
   * The ID of the tool call this result corresponds to.
   */
  toolCallId: string;
  /**
   * The name of the tool executed (e.g. "readFile", "bash").
   */
  toolName?: string;
  /**
   * The content or output generated by the tool.
   */
  content: unknown;
  /**
   * An optional flag to indicate if the tool execution resulted in an error.
   */
  isError?: boolean;
}

/**
 * The core interface for defining a tool that can be used by the agent.
 *
 * @template T - The Zod schema for the tool's input arguments.
 */
export interface AgentTool<T extends z.ZodTypeAny = z.ZodTypeAny> {
  /**
   * The name of the tool. Must be a single word, using underscores if necessary
   * (e.g., "readFile", "search_web"). This is the name the model will use to call the tool.
   */
  name: string;
  /**
   * A detailed description of what the tool does, what it's for, and what its
   * parameters mean. This is critical for the model to understand when and how
   * to use the tool.
   */
  description: string;
  /**
   * Capability tier ("read" | "write" | "exec"). Defaults to "read" if omitted.
   */
  tier?: ToolTier;
  /**
   * A schema from the 'zod' library that defines the shape, types, and validation
   * rules for the tool's input arguments.
   */
  inputSchema: T;
  /**
   * The asynchronous function that executes the tool's logic.
   * @param args - The input arguments, parsed and validated against the `inputSchema`.
   * @returns A promise that resolves to the tool's output. This can be any data type.
   */
  execute: (args: z.infer<T>) => Promise<unknown>;
}

/**
 * A standardized error class for tool executions.
 * Use this to signal a failure in a tool's execution back to the agent harness.
 */
export class ToolError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ToolError";
  }
}
