import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    backgroundColor: "#0d0d0e",
    alignItems: "center",
    justifyContent: "center",
  },
  appContainer: {
    flex: 1,
    backgroundColor: "#0d0d0e",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#0d0d0e",
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#f1f3f7",
    marginBottom: 16,
    letterSpacing: -0.5,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  emptyText: {
    color: "#9095a0",
    textAlign: "center",
    fontSize: 14,
  },
  addProjectBar: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  projectInput: {
    flex: 1,
    height: 40,
    backgroundColor: "#16171a",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 8,
    paddingHorizontal: 12,
    color: "#f1f3f7",
    fontSize: 13,
  },
  projectAddBtn: {
    height: 40,
    backgroundColor: "#f1f3f7",
    borderRadius: 8,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  projectAddBtnText: {
    color: "#09090b",
    fontSize: 13,
    fontWeight: "600",
  },
  projectCard: {
    backgroundColor: "#121316",
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.05)",
    overflow: "hidden",
  },
  projectHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
  },
  projectHeaderActive: {
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  projectTitle: {
    color: "#9095a0",
    fontSize: 14,
    fontWeight: "500",
  },
  projectTitleActive: {
    color: "#f1f3f7",
  },
  sessionsContainer: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.04)",
  },
  sessionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    marginTop: 4,
  },
  sessionsTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#9095a0",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  newSessionBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  newSessionBtnText: {
    color: "#f1f3f7",
    fontSize: 10,
    fontWeight: "600",
  },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginBottom: 4,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  sessionRowActive: {
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  sessionClickArea: {
    flex: 1,
    paddingRight: 10,
  },
  sessionText: {
    color: "#9095a0",
    fontSize: 12,
  },
  sessionTextActive: {
    color: "#f1f3f7",
    fontWeight: "500",
  },
  sessionDeleteBtn: {
    padding: 4,
  },
  sessionDeleteText: {
    color: "#ef4444",
    fontSize: 11,
  },
  emptySessionsText: {
    fontSize: 11,
    color: "#9095a0",
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    padding: 24,
  },
  modalContent: {
    backgroundColor: "#121316",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#f1f3f7",
    marginBottom: 6,
  },
  modalSub: {
    fontSize: 13,
    color: "#9095a0",
    marginBottom: 16,
  },
  input: {
    height: 44,
    backgroundColor: "#16171a",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 8,
    paddingHorizontal: 12,
    color: "#f1f3f7",
    fontSize: 14,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  btn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
  },
  btnCancel: {
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  btnSave: {
    backgroundColor: "#f1f3f7",
  },
  btnText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#09090b",
  },
  bottomBar: {
    height: 60,
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#080809",
    paddingBottom: Platform.OS === "ios" ? 10 : 0,
  },
  tabButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  tabText: {
    color: "#9095a0",
    fontSize: 12,
    fontWeight: "500",
  },
  tabTextActive: {
    color: "#38bdf8",
  },
  tabTextSettings: {
    color: "#9095a0",
    fontSize: 12,
    fontWeight: "500",
  },
  chatContainer: {
    flex: 1,
    paddingTop: 12,
  },
  messageList: {
    flex: 1,
  },
  messageContentList: {
    paddingHorizontal: 16,
    paddingBottom: 80,
  },
  bubbleContainer: {
    padding: 12,
    borderRadius: 10,
    marginBottom: 12,
    maxWidth: "85%",
  },
  bubbleUser: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    alignSelf: "flex-end",
  },
  bubbleAgent: {
    backgroundColor: "#121316",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    alignSelf: "flex-start",
    width: "100%",
    maxWidth: "90%",
  },
  bubbleRole: {
    fontSize: 10,
    fontWeight: "700",
    color: "#9095a0",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  bubbleText: {
    color: "#f1f3f7",
    fontSize: 13,
    lineHeight: 18,
  },
  chatComposer: {
    flexDirection: "row",
    gap: 8,
    padding: 12,
    backgroundColor: "#0d0d0e",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
  },
  chatInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 100,
    backgroundColor: "#16171a",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: "#f1f3f7",
    fontSize: 13,
  },
  chatSendBtn: {
    height: 40,
    backgroundColor: "#f1f3f7",
    borderRadius: 8,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  chatSendBtnDisabled: {
    opacity: 0.3,
  },
  chatSendBtnText: {
    color: "#09090b",
    fontSize: 13,
    fontWeight: "600",
  },
  emptyList: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyListText: {
    color: "#9095a0",
    fontSize: 12,
    fontStyle: "italic",
  },
});
