/**
 * AUTO-GENERATED by scripts/generate-theme.mjs — do not edit by hand.
 * Mirrors the @theme color tokens in global.css (the single source of truth).
 * Regenerate with: npm run theme:generate
 *
 * Prefer className utilities (bg-screen, text-foreground-secondary, ...) when
 * possible; use these values only for props/styles that need raw strings
 * (icon color, inline style objects, third-party components).
 */
export const theme = {
  colors: {
    /** --color-screen */
    background: "#0a0a0b",
    /** --color-screen (alias kept for existing call sites) */
    backgroundAlt: "#0a0a0b",
    /** --color-surface */
    surface: "#16171a",
    /** --color-surface-elevated */
    surfaceElevated: "#1f2024",
    /** --color-border */
    border: "rgba(255, 255, 255, 0.12)",
    /** --color-border-subtle */
    borderSubtle: "rgba(255, 255, 255, 0.06)",

    // Text colors
    text: {
      /** --color-foreground */
      primary: "#ffffff",
      /** --color-foreground-secondary */
      secondary: "#a1a1aa",
      /** --color-foreground-muted */
      muted: "#71717a",
      dark: "#000000",
    },

    // Status colors (hex from --color-status-*; bg variants are 10% tints)
    status: {
      running: "#fb923c",
      runningBg: "rgba(251, 146, 60, 0.1)",
      ready: "#34d399",
      readyBg: "rgba(52, 211, 153, 0.1)",
      attention: "#f87171",
      attentionBg: "rgba(248, 113, 113, 0.1)",
      idle: "#a1a1aa",
      idleBg: "rgba(161, 161, 170, 0.1)",
    },

    // Destructive — --color-destructive
    danger: "#f87171",
    dangerPressed: "#dc2626",
  },

  fonts: {
    mono: "JetBrainsMono",
    monoMedium: "JetBrainsMono-Medium",
    monoSemiBold: "JetBrainsMono-SemiBold",
    monoBold: "JetBrainsMono-Bold",
  },

  roundness: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 9999,
  },

  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
};
