import Foundation
import JavaScriptCore
import os

/// Package-private logging handle: CodeHighlighter must not depend on
/// CodevisorCore, so it carries its own `Logger` under the app's shared
/// subsystem.
private let log = Logger(subsystem: "com.851labs.codevisor", category: "highlighting")

/// Syntax highlighting via Shiki running inside JavaScriptCore. The bundled
/// `highlighter.js` (generated by apps/macos/scripts/build-highlighter.mjs)
/// carries Shiki's pure-JavaScript regex engine plus a curated grammar set;
/// themes are passed in as raw VSCode/Shiki theme JSON, so any theme the app
/// can load highlights exactly as it would in VSCode.
///
/// An actor: the 2 MB bundle is evaluated lazily on first use, off the main
/// thread, and all JSContext access is serialized. Results are cached per
/// (code, language, theme) — streaming re-renders hit the cache for free.
public actor CodeHighlighter {
    /// One token of highlighted output; `color` is a hex string or nil for
    /// the theme's default foreground.
    public struct Token: Sendable, Equatable, Codable {
        public let content: String
        public let color: String?
    }

    public static let shared = CodeHighlighter()

    private var context: JSContext?
    private var loadFailed = false
    private var cache: [String: [[Token]]] = [:]
    private var cacheOrder: [String] = []
    private let cacheLimit = 200

    public init() {}

    /// Grammar name for a file path's extension, or nil when the bundled set
    /// has no grammar for it (caller keeps plain text). Mirrors the alias map
    /// in highlighter-entry.mjs plus extension-only spellings (rs, h, hpp…)
    /// that markdown fences never use.
    public static func language(forPath path: String) -> String? {
        let ext = (path as NSString).pathExtension.lowercased()
        guard !ext.isEmpty else { return nil }
        return extensionLanguages[ext]
    }

    private static let extensionLanguages: [String: String] = [
        "sh": "bash", "bash": "bash", "zsh": "bash",
        "c": "c", "h": "c",
        "cpp": "cpp", "cc": "cpp", "cxx": "cpp", "hpp": "cpp", "hh": "cpp",
        "css": "css",
        "diff": "diff", "patch": "diff",
        "go": "go",
        "html": "html", "htm": "html",
        "java": "java",
        "js": "javascript", "mjs": "javascript", "cjs": "javascript",
        "json": "json", "jsonc": "json",
        "jsx": "jsx",
        "kt": "kotlin", "kts": "kotlin",
        "md": "markdown", "markdown": "markdown",
        "py": "python",
        "rb": "ruby",
        "rs": "rust",
        "sql": "sql",
        "swift": "swift",
        "toml": "toml",
        "tsx": "tsx",
        "ts": "typescript", "mts": "typescript", "cts": "typescript",
        "yml": "yaml", "yaml": "yaml",
    ]

    /// Tokenizes `code` under the given theme, or returns nil when the
    /// language is unknown/unsupported or the highlighter can't run (the
    /// caller keeps plain text). `themeKey` must be a stable identity for the
    /// theme JSON (its id) — it keys both caches.
    public func highlight(
        code: String,
        language: String?,
        themeKey: String,
        themeJSON: String
    ) -> [[Token]]? {
        guard let language, !language.isEmpty else { return nil }

        let cacheKey = "\(themeKey)|\(language)|\(code.hashValue)"
        if let cached = cache[cacheKey] { return cached }

        guard let function = highlightFunction() else { return nil }
        let result = function.call(withArguments: [code, language, themeKey, themeJSON])
        guard
            let json = result?.toString(), json != "null",
            let data = json.data(using: .utf8)
        else { return nil }
        let tokens: [[Token]]
        do {
            tokens = try JSONDecoder().decode([[Token]].self, from: data)
        } catch {
            log.error(
                "Failed to decode highlight tokens for language \(language, privacy: .public): \(String(describing: error), privacy: .public)"
            )
            return nil
        }

        cache[cacheKey] = tokens
        cacheOrder.append(cacheKey)
        if cacheOrder.count > cacheLimit {
            cache.removeValue(forKey: cacheOrder.removeFirst())
        }
        return tokens
    }

    // Evaluates the bundle once and returns the global highlight function.
    // A failed load is remembered so a broken bundle degrades to plain text
    // without retrying on every block.
    private func highlightFunction() -> JSValue? {
        if let context {
            return context.objectForKeyedSubscript("codevisorHighlight")
        }
        guard !loadFailed else { return nil }
        guard
            let url = Bundle.module.url(forResource: "highlighter", withExtension: "js"),
            let source = try? String(contentsOf: url, encoding: .utf8),
            let jsContext = JSContext()
        else {
            loadFailed = true
            log.fault(
                "highlighter.js missing or unreadable — all syntax highlighting disabled for this session"
            )
            return nil
        }
        jsContext.exceptionHandler = { _, exception in
            log.error(
                "JavaScript exception in highlighter: \(exception?.toString() ?? "unknown", privacy: .public)"
            )
        }
        jsContext.evaluateScript(source)
        let function = jsContext.objectForKeyedSubscript("codevisorHighlight")
        guard let function, !function.isUndefined else {
            loadFailed = true
            log.fault(
                "highlighter.js loaded but codevisorHighlight is missing — all syntax highlighting disabled for this session"
            )
            return nil
        }
        context = jsContext
        return function
    }
}
