// Host environment for the embedded driver on macOS.
//
// The driver needs to know it runs inside our grant-owning bundle, which is
// communicated through two variables: CUA_DRIVER_EMBEDDED and
// CUA_DRIVER_HOST_BUNDLE_ID. Rather than depending on launchctl state set up
// by hand, the process derives them itself: embedded mode is always correct on
// macOS (the binary lives inside the bundle whose grant it uses), and the
// bundle identifier is read from the process's own Info.plist.
package cua

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

const (
	// EnvEmbedded tells the driver it runs inside the host's TCC chain.
	EnvEmbedded = "CUA_DRIVER_EMBEDDED"
	// EnvHostBundleID is the bundle identifier the driver reports against.
	EnvHostBundleID = "CUA_DRIVER_HOST_BUNDLE_ID"
)

// EnsureHostEnv defaults the embedded-mode variables on macOS when the caller
// did not set them explicitly, and returns the bundle identifier in effect
// (empty when the process is not inside a bundle).
func EnsureHostEnv() string {
	if runtime.GOOS != "darwin" {
		return ""
	}
	if os.Getenv(EnvEmbedded) == "" {
		_ = os.Setenv(EnvEmbedded, "1")
	}
	if os.Getenv(EnvHostBundleID) == "" {
		if id := ownBundleID(); id != "" {
			_ = os.Setenv(EnvHostBundleID, id)
		}
	}
	return os.Getenv(EnvHostBundleID)
}

// PlistStringForTest exposes the plist scan so its behaviour is pinned without
// needing a real bundle on disk.
func PlistStringForTest(plist, key string) string { return plistStringValue(plist, key) }
func ownBundleID() string {
	exe, err := os.Executable()
	if err != nil {
		return ""
	}
	if exe, err = filepath.EvalSymlinks(exe); err != nil {
		return ""
	}
	// .../Name.app/Contents/MacOS/<binary>
	macOSDir := filepath.Dir(exe)
	contentsDir := filepath.Dir(macOSDir)
	appDir := filepath.Dir(contentsDir)
	if filepath.Base(macOSDir) != "MacOS" ||
		filepath.Base(contentsDir) != "Contents" ||
		!strings.HasSuffix(appDir, ".app") {
		return ""
	}
	raw, err := os.ReadFile(filepath.Join(contentsDir, "Info.plist"))
	if err != nil {
		return ""
	}
	return plistStringValue(string(raw), "CFBundleIdentifier")
}

// plistStringValue extracts one <string> value for a <key> from a plist
// without a plist parser. The plists involved are generated by our own bundle
// builder, so a flat scan is sufficient and keeps this dependency-free.
func plistStringValue(plist, key string) string {
	i := strings.Index(plist, "<key>"+key+"</key>")
	if i < 0 {
		return ""
	}
	rest := plist[i:]
	s := strings.Index(rest, "<string>")
	if s < 0 {
		return ""
	}
	rest = rest[s+len("<string>"):]
	e := strings.Index(rest, "</string>")
	if e < 0 {
		return ""
	}
	return rest[:e]
}
