#!/usr/bin/env node
/**
 * Generates styles/theme.ts from the @theme tokens in global.css,
 * so the JS theme can never diverge from the CSS design tokens.
 *
 * Usage: bun scripts/generate-theme.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "global.css"), "utf8");

// Parse --color-* tokens out of the @theme block.
const tokens = {};
for (const [, name, value] of css.matchAll(/--color-([a-z0-9-]+):\s*([^;]+);/g)) {
  tokens[name.trim()] = value.trim();
}

const need = [
  "screen",
  "surface",
  "surface-elevated",
  "border",
  "border-subtle",
  "foreground",
  "foreground-secondary",
  "foreground-muted",
  "destructive",
  "status-running",
  "status-ready",
  "status-attention",
  "status-idle",
];
const missing = need.filter((n) => !(n in tokens));
if (missing.length) {
  console.error(`Missing required --color-* tokens in global.css: ${missing.join(", ")}`);
  process.exit(1);
}

const v = (name) => tokens[name];
const out = `/**
 * AUTO-GENERATED by scripts/generate-theme.mjs — do not edit by hand.
 * Mirrors the @theme color tokens in global.css (the single source of truth).
 * Regenerate with: bun run theme:generate
 *
 * Prefer className utilities (bg-screen, text-foreground-secondary, ...) when
 * possible; use these values only for props/styles that need raw strings
 * (icon color, inline style objects, third-party components).
 */
export const theme = {
  colors: {
    /** --color-screen */
    background: "${v("screen")}",
    /** --color-screen (alias kept for existing call sites) */
    backgroundAlt: "${v("screen")}",
    /** --color-surface */
    surface: "${v("surface")}",
    /** --color-surface-elevated */
    surfaceElevated: "${v("surface-elevated")}",
    /** --color-border */
    border: "${v("border")}",
    /** --color-border-subtle */
    borderSubtle: "${v("border-subtle")}",

    // Text colors
    text: {
      /** --color-foreground */
      primary: "${v("foreground")}",
      /** --color-foreground-secondary */
      secondary: "${v("foreground-secondary")}",
      /** --color-foreground-muted */
      muted: "${v("foreground-muted")}",
      dark: "#000000",
    },

    // Status colors (hex from --color-status-*; bg variants are 10% tints)
    status: {
      running: "${v("status-running")}",
      runningBg: "rgba(251, 146, 60, 0.1)",
      ready: "${v("status-ready")}",
      readyBg: "rgba(52, 211, 153, 0.1)",
      attention: "${v("status-attention")}",
      attentionBg: "rgba(248, 113, 113, 0.1)",
      idle: "${v("status-idle")}",
      idleBg: "rgba(161, 161, 170, 0.1)",
    },

    // Destructive — --color-destructive
    danger: "${v("destructive")}",
    dangerPressed: "#dc2626",
  },

  fonts: {
    mono: "JetBrainsMono",
    monoMedium: "JetBrainsMono-Medium",
    monoSemiBold: "JetBrainsMono-SemiBold",
    monoBold: "JetBrainsMono-Bold",
  },

  roundness: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 9999,
  },

  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
};
`;

writeFileSync(join(root, "styles/theme.ts"), out);
console.log(`Generated styles/theme.ts from ${need.length} CSS color tokens.`);
