//! Typed names for the complete shared application icon set.
//!
//! Existing callers may continue using `crate::primitives::icon` while code is
//! migrated in batches. New code should prefer [`app_icon`], [`ProviderIcon`],
//! and [`FileTypeIcon`] so asset paths are centralized and checked in one place.

use gpui::{Hsla, Styled, Svg, px, svg};

/// An icon from the root `assets/icons` directory.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum IconName {
    TriangleAlert,
    Search,
    ArrowDown,
    Queue,
    List,
    Inspector,
    Magnifer,
    PanelRightClose,
    MemoryStick,
    Restart,
    SortDescending,
    User,
    ReplaceAll,
    SidebarMinimalistic,
    ChevronsUpDown,
    Alert,
    Circle,
    WindowRestore,
    Smartphone,
    ChevronDown,
    Hexagon,
    Github,
    PanelRightOpen,
    StarOff,
    Redo2,
    Tag,
    Sparkle,
    RotateCw,
    EllipsisVertical,
    Map,
    Inbox,
    ALargeSmall,
    File,
    Terminal,
    Maximize,
    ChevronUp,
    Undo2,
    FolderOpen,
    DocumentAdd,
    WholeWord,
    Keyboard,
    X,
    Lock,
    CloudUpload,
    BatteryWarning,
    Pen,
    ChevronRight,
    StarFill,
    Package,
    CornerDownRight,
    ArrowRight,
    FolderWithFiles,
    DangerTriangle,
    CursorSpark,
    Return,
    Minimize,
    Settings,
    AltArrowDown,
    ThumbsDown,
    Compose,
    Regex,
    LoaderCircle,
    CloseCircle,
    Download,
    GalleryVerticalEnd,
    BookOpen,
    Server,
    BatteryMedium,
    BatteryCharging,
    Slash,
    Bot,
    CircleCheck,
    FolderNew,
    Bell,
    GitBranch,
    Settings2,
    StarFilled,
    EyeOff,
    Battery,
    ArchiveUpMinimalistic,
    TrashBinMinimalistic,
    Stop,
    VolumeLoud,
    LayoutDashboard,
    Cpu,
    BatteryFull,
    Plus,
    PanelBottom,
    Document,
    Check,
    Dash,
    HardDrive,
    CaseSensitive,
    Global,
    ArchiveMinimalistic,
    Info,
    Loader,
    Palette,
    SettingsMinimalistic,
    Close,
    InfoCircle,
    Copy,
    AltArrowRight,
    PanelLeft,
    Refresh,
    PanelBottomOpen,
    Fork,
    AltArrowLeft,
    Paperclip,
    Appearance,
    KeyMinimalistic,
    ThumbsUp,
    BatteryLow,
    Play,
    PanelLeftClose,
    Redo,
    ArrowUpRight,
    SquareTerminal,
    Widget,
    WifiOff,
    Network,
    WindowMaximize,
    Star,
    Sun,
    Wrench,
    Checklist,
    Gauge,
    ChartColumn,
    ChartPie,
    ExpandArrows,
    Changes,
    Frame,
    HeartOff,
    TerminalSquare,
    Pencil,
    WindowClose,
    CircleUser,
    Delete,
    StopFilled,
    Command,
    WindowMinimize,
    CircleX,
    ResizeCorner,
    PanelLeftOpen,
    FolderClosed,
    Eye,
    ExternalLink,
    Zap,
    StarBold,
    Building2,
    ArrowUp,
    PanelRight,
    PenNewSquare,
    Undo,
    ChatRoundLine,
    AddCircle,
    Calendar,
    Globe,
    ArrowLeft,
    Ellipsis,
    Laptop,
    Cloud,
    Rewind,
    FoldVertical,
    Pause,
    Logout2,
    SidebarMinimalisticLeft,
    Replace,
    Asterisk,
    FileDiff,
    SortVertical,
    LockOpen,
    Menu,
    SortAscending,
    Block,
    Folder,
    GitCommitHorizontal,
    Monitor,
    Minus,
    ChevronLeft,
    Moon,
    Tuning,
    Heart,
    Provider(ProviderIcon),
    FileType(FileTypeIcon),
}

/// Provider logos from both the root and `icons/providers` asset directories.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ProviderIcon {
    Gemini,
    Codebuff,
    Antigravity,
    Openai,
    OpenaiNested,
    Opencode,
    OpencodeNested,
    Claude,
    Deepseek,
    Grok,
    Cursor,
    Amp,
    Pi,
}

/// File-type logos from `assets/icons/file-types`.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum FileTypeIcon {
    Pnpm,
    Elm,
    Turborepo,
    Webpack,
    Jinja,
    Javascript,
    Vue,
    Xml,
    Vitest,
    Gitlab,
    Sass,
    Rust,
    Pug,
    Supabase,
    Firebase,
    Java,
    Haskell,
    Database,
    Solidity,
    Helm,
    File,
    Biome,
    Nix,
    Npm,
    Nuxt,
    Cpp,
    Angular,
    Zig,
    Zip,
    Lock,
    Scala,
    Perl,
    Json,
    Certificate,
    Ruby,
    Diff,
    Settings,
    Python,
    Xaml,
    Docker,
    Git,
    Kubernetes,
    Powershell,
    Coffee,
    Erlang,
    Markdown,
    Vite,
    Bun,
    Lua,
    Tex,
    Nodejs,
    Kotlin,
    Elixir,
    Readme,
    Image,
    Prettier,
    Terraform,
    Yarn,
    Ocaml,
    Dart,
    Svelte,
    Julia,
    Svg,
    Eslint,
    Makefile,
    Css,
    Php,
    Typescript,
    Rollup,
    C,
    Next,
    Editorconfig,
    Pdf,
    Babel,
    Proto,
    Audio,
    Yaml,
    Astro,
    Storybook,
    Tailwindcss,
    Nest,
    Stylelint,
    Clojure,
    Video,
    React,
    Swift,
    Cmake,
    Html,
    Console,
    Deno,
    Crystal,
    Csharp,
    Graphql,
    Nginx,
    Go,
    Prisma,
    Haxe,
    Exe,
    Webassembly,
    Gradle,
}

impl IconName {
    /// Return the embedded asset path for this icon.
    pub const fn path(self) -> &'static str {
        match self {
            Self::TriangleAlert => "icons/triangle-alert.svg",
            Self::Search => "icons/search.svg",
            Self::ArrowDown => "icons/arrow-down.svg",
            Self::Queue => "icons/queue.svg",
            Self::List => "icons/list.svg",
            Self::Inspector => "icons/inspector.svg",
            Self::Magnifer => "icons/magnifer.svg",
            Self::PanelRightClose => "icons/panel-right-close.svg",
            Self::MemoryStick => "icons/memory-stick.svg",
            Self::Restart => "icons/restart.svg",
            Self::SortDescending => "icons/sort-descending.svg",
            Self::User => "icons/user.svg",
            Self::ReplaceAll => "icons/replace-all.svg",
            Self::SidebarMinimalistic => "icons/sidebar-minimalistic.svg",
            Self::ChevronsUpDown => "icons/chevrons-up-down.svg",
            Self::Alert => "icons/alert.svg",
            Self::Circle => "icons/circle.svg",
            Self::WindowRestore => "icons/window-restore.svg",
            Self::Smartphone => "icons/smartphone.svg",
            Self::ChevronDown => "icons/chevron-down.svg",
            Self::Hexagon => "icons/hexagon.svg",
            Self::Github => "icons/github.svg",
            Self::PanelRightOpen => "icons/panel-right-open.svg",
            Self::StarOff => "icons/star-off.svg",
            Self::Redo2 => "icons/redo-2.svg",
            Self::Tag => "icons/tag.svg",
            Self::Sparkle => "icons/sparkle.svg",
            Self::RotateCw => "icons/rotate-cw.svg",
            Self::EllipsisVertical => "icons/ellipsis-vertical.svg",
            Self::Map => "icons/map.svg",
            Self::Inbox => "icons/inbox.svg",
            Self::ALargeSmall => "icons/a-large-small.svg",
            Self::File => "icons/file.svg",
            Self::Terminal => "icons/terminal.svg",
            Self::Maximize => "icons/maximize.svg",
            Self::ChevronUp => "icons/chevron-up.svg",
            Self::Undo2 => "icons/undo-2.svg",
            Self::FolderOpen => "icons/folder-open.svg",
            Self::DocumentAdd => "icons/document-add.svg",
            Self::WholeWord => "icons/whole-word.svg",
            Self::Keyboard => "icons/keyboard.svg",
            Self::X => "icons/x.svg",
            Self::Lock => "icons/lock.svg",
            Self::CloudUpload => "icons/cloud-upload.svg",
            Self::BatteryWarning => "icons/battery-warning.svg",
            Self::Pen => "icons/pen.svg",
            Self::ChevronRight => "icons/chevron-right.svg",
            Self::StarFill => "icons/star-fill.svg",
            Self::Package => "icons/package.svg",
            Self::CornerDownRight => "icons/corner-down-right.svg",
            Self::ArrowRight => "icons/arrow-right.svg",
            Self::FolderWithFiles => "icons/folder-with-files.svg",
            Self::DangerTriangle => "icons/danger-triangle.svg",
            Self::CursorSpark => "icons/cursor-spark.svg",
            Self::Return => "icons/return.svg",
            Self::Minimize => "icons/minimize.svg",
            Self::Settings => "icons/settings.svg",
            Self::AltArrowDown => "icons/alt-arrow-down.svg",
            Self::ThumbsDown => "icons/thumbs-down.svg",
            Self::Compose => "icons/compose.svg",
            Self::Regex => "icons/regex.svg",
            Self::LoaderCircle => "icons/loader-circle.svg",
            Self::CloseCircle => "icons/close-circle.svg",
            Self::Download => "icons/download.svg",
            Self::GalleryVerticalEnd => "icons/gallery-vertical-end.svg",
            Self::BookOpen => "icons/book-open.svg",
            Self::Server => "icons/server.svg",
            Self::BatteryMedium => "icons/battery-medium.svg",
            Self::BatteryCharging => "icons/battery-charging.svg",
            Self::Slash => "icons/slash.svg",
            Self::Bot => "icons/bot.svg",
            Self::CircleCheck => "icons/circle-check.svg",
            Self::FolderNew => "icons/folder-new.svg",
            Self::Bell => "icons/bell.svg",
            Self::GitBranch => "icons/git-branch.svg",
            Self::Settings2 => "icons/settings-2.svg",
            Self::StarFilled => "icons/star-filled.svg",
            Self::EyeOff => "icons/eye-off.svg",
            Self::Battery => "icons/battery.svg",
            Self::ArchiveUpMinimalistic => "icons/archive-up-minimalistic.svg",
            Self::TrashBinMinimalistic => "icons/trash-bin-minimalistic.svg",
            Self::Stop => "icons/stop.svg",
            Self::VolumeLoud => "icons/volume-loud.svg",
            Self::LayoutDashboard => "icons/layout-dashboard.svg",
            Self::Cpu => "icons/cpu.svg",
            Self::BatteryFull => "icons/battery-full.svg",
            Self::Plus => "icons/plus.svg",
            Self::PanelBottom => "icons/panel-bottom.svg",
            Self::Document => "icons/document.svg",
            Self::Check => "icons/check.svg",
            Self::Dash => "icons/dash.svg",
            Self::HardDrive => "icons/hard-drive.svg",
            Self::CaseSensitive => "icons/case-sensitive.svg",
            Self::Global => "icons/global.svg",
            Self::ArchiveMinimalistic => "icons/archive-minimalistic.svg",
            Self::Info => "icons/info.svg",
            Self::Loader => "icons/loader.svg",
            Self::Palette => "icons/palette.svg",
            Self::SettingsMinimalistic => "icons/settings-minimalistic.svg",
            Self::Close => "icons/close.svg",
            Self::InfoCircle => "icons/info-circle.svg",
            Self::Copy => "icons/copy.svg",
            Self::AltArrowRight => "icons/alt-arrow-right.svg",
            Self::PanelLeft => "icons/panel-left.svg",
            Self::Refresh => "icons/refresh.svg",
            Self::PanelBottomOpen => "icons/panel-bottom-open.svg",
            Self::Fork => "icons/fork.svg",
            Self::AltArrowLeft => "icons/alt-arrow-left.svg",
            Self::Paperclip => "icons/paperclip.svg",
            Self::Appearance => "icons/appearance.svg",
            Self::KeyMinimalistic => "icons/key-minimalistic.svg",
            Self::ThumbsUp => "icons/thumbs-up.svg",
            Self::BatteryLow => "icons/battery-low.svg",
            Self::Play => "icons/play.svg",
            Self::PanelLeftClose => "icons/panel-left-close.svg",
            Self::Redo => "icons/redo.svg",
            Self::ArrowUpRight => "icons/arrow-up-right.svg",
            Self::SquareTerminal => "icons/square-terminal.svg",
            Self::Widget => "icons/widget.svg",
            Self::WifiOff => "icons/wifi-off.svg",
            Self::Network => "icons/network.svg",
            Self::WindowMaximize => "icons/window-maximize.svg",
            Self::Star => "icons/star.svg",
            Self::Sun => "icons/sun.svg",
            Self::Wrench => "icons/wrench.svg",
            Self::Checklist => "icons/checklist.svg",
            Self::Gauge => "icons/gauge.svg",
            Self::ChartColumn => "icons/chart-column.svg",
            Self::ChartPie => "icons/chart-pie.svg",
            Self::ExpandArrows => "icons/expand-arrows.svg",
            Self::Changes => "icons/changes.svg",
            Self::Frame => "icons/frame.svg",
            Self::HeartOff => "icons/heart-off.svg",
            Self::TerminalSquare => "icons/terminal-square.svg",
            Self::Pencil => "icons/pencil.svg",
            Self::WindowClose => "icons/window-close.svg",
            Self::CircleUser => "icons/circle-user.svg",
            Self::Delete => "icons/delete.svg",
            Self::StopFilled => "icons/stop-filled.svg",
            Self::Command => "icons/command.svg",
            Self::WindowMinimize => "icons/window-minimize.svg",
            Self::CircleX => "icons/circle-x.svg",
            Self::ResizeCorner => "icons/resize-corner.svg",
            Self::PanelLeftOpen => "icons/panel-left-open.svg",
            Self::FolderClosed => "icons/folder-closed.svg",
            Self::Eye => "icons/eye.svg",
            Self::ExternalLink => "icons/external-link.svg",
            Self::Zap => "icons/zap.svg",
            Self::StarBold => "icons/star-bold.svg",
            Self::Building2 => "icons/building-2.svg",
            Self::ArrowUp => "icons/arrow-up.svg",
            Self::PanelRight => "icons/panel-right.svg",
            Self::PenNewSquare => "icons/pen-new-square.svg",
            Self::Undo => "icons/undo.svg",
            Self::ChatRoundLine => "icons/chat-round-line.svg",
            Self::AddCircle => "icons/add-circle.svg",
            Self::Calendar => "icons/calendar.svg",
            Self::Globe => "icons/globe.svg",
            Self::ArrowLeft => "icons/arrow-left.svg",
            Self::Ellipsis => "icons/ellipsis.svg",
            Self::Laptop => "icons/laptop.svg",
            Self::Cloud => "icons/cloud.svg",
            Self::Rewind => "icons/rewind.svg",
            Self::FoldVertical => "icons/fold-vertical.svg",
            Self::Pause => "icons/pause.svg",
            Self::Logout2 => "icons/logout-2.svg",
            Self::SidebarMinimalisticLeft => "icons/sidebar-minimalistic-left.svg",
            Self::Replace => "icons/replace.svg",
            Self::Asterisk => "icons/asterisk.svg",
            Self::FileDiff => "icons/file-diff.svg",
            Self::SortVertical => "icons/sort-vertical.svg",
            Self::LockOpen => "icons/lock-open.svg",
            Self::Menu => "icons/menu.svg",
            Self::SortAscending => "icons/sort-ascending.svg",
            Self::Block => "icons/block.svg",
            Self::Folder => "icons/folder.svg",
            Self::GitCommitHorizontal => "icons/git-commit-horizontal.svg",
            Self::Monitor => "icons/monitor.svg",
            Self::Minus => "icons/minus.svg",
            Self::ChevronLeft => "icons/chevron-left.svg",
            Self::Moon => "icons/moon.svg",
            Self::Tuning => "icons/tuning.svg",
            Self::Heart => "icons/heart.svg",
            Self::Provider(provider) => provider.path(),
            Self::FileType(file_type) => file_type.path(),
        }
    }

    /// Render this icon using the same sizing and tinting as the legacy helper.
    pub fn render(self, size: f32, color: Hsla) -> Svg {
        svg()
            .path(self.path())
            .w(px(size))
            .h(px(size))
            .flex_none()
            .text_color(color)
    }

    /// Resolve a provider name to its typed icon.
    pub fn provider(name: &str) -> Self {
        Self::Provider(ProviderIcon::from_name(name))
    }
}

impl ProviderIcon {
    pub fn from_name(name: &str) -> Self {
        match name.to_ascii_lowercase().as_str() {
            "gemini" | "google" => Self::Gemini,
            "codebuff" => Self::Codebuff,
            "antigravity" => Self::Antigravity,
            "openai" | "codex" | "chatgpt" => Self::OpenaiNested,
            "opencode" => Self::OpencodeNested,
            "claude" | "anthropic" => Self::Claude,
            "deepseek" => Self::Deepseek,
            "grok" => Self::Grok,
            "cursor" => Self::Cursor,
            "amp" => Self::Amp,
            "pi" => Self::Pi,
            _ => Self::Openai,
        }
    }

    pub const fn path(self) -> &'static str {
        match self {
            Self::Gemini => "icons/providers/gemini.svg",
            Self::Codebuff => "icons/providers/codebuff.svg",
            Self::Antigravity => "icons/providers/antigravity.svg",
            Self::Openai => "icons/provider-openai.svg",
            Self::OpenaiNested => "icons/providers/openai.svg",
            Self::Opencode => "icons/provider-opencode.svg",
            Self::OpencodeNested => "icons/providers/opencode.svg",
            Self::Claude => "icons/provider-claude.svg",
            Self::Deepseek => "icons/provider-deepseek.svg",
            Self::Grok => "icons/provider-grok.svg",
            Self::Cursor => "icons/provider-cursor.svg",
            Self::Amp => "icons/provider-amp.svg",
            Self::Pi => "icons/provider-pi.svg",
        }
    }
}

impl FileTypeIcon {
    pub const fn path(self) -> &'static str {
        match self {
            Self::Pnpm => "icons/file-types/pnpm.svg",
            Self::Elm => "icons/file-types/elm.svg",
            Self::Turborepo => "icons/file-types/turborepo.svg",
            Self::Webpack => "icons/file-types/webpack.svg",
            Self::Jinja => "icons/file-types/jinja.svg",
            Self::Javascript => "icons/file-types/javascript.svg",
            Self::Vue => "icons/file-types/vue.svg",
            Self::Xml => "icons/file-types/xml.svg",
            Self::Vitest => "icons/file-types/vitest.svg",
            Self::Gitlab => "icons/file-types/gitlab.svg",
            Self::Sass => "icons/file-types/sass.svg",
            Self::Rust => "icons/file-types/rust.svg",
            Self::Pug => "icons/file-types/pug.svg",
            Self::Supabase => "icons/file-types/supabase.svg",
            Self::Firebase => "icons/file-types/firebase.svg",
            Self::Java => "icons/file-types/java.svg",
            Self::Haskell => "icons/file-types/haskell.svg",
            Self::Database => "icons/file-types/database.svg",
            Self::Solidity => "icons/file-types/solidity.svg",
            Self::Helm => "icons/file-types/helm.svg",
            Self::File => "icons/file-types/file.svg",
            Self::Biome => "icons/file-types/biome.svg",
            Self::Nix => "icons/file-types/nix.svg",
            Self::Npm => "icons/file-types/npm.svg",
            Self::Nuxt => "icons/file-types/nuxt.svg",
            Self::Cpp => "icons/file-types/cpp.svg",
            Self::Angular => "icons/file-types/angular.svg",
            Self::Zig => "icons/file-types/zig.svg",
            Self::Zip => "icons/file-types/zip.svg",
            Self::Lock => "icons/file-types/lock.svg",
            Self::Scala => "icons/file-types/scala.svg",
            Self::Perl => "icons/file-types/perl.svg",
            Self::Json => "icons/file-types/json.svg",
            Self::Certificate => "icons/file-types/certificate.svg",
            Self::Ruby => "icons/file-types/ruby.svg",
            Self::Diff => "icons/file-types/diff.svg",
            Self::Settings => "icons/file-types/settings.svg",
            Self::Python => "icons/file-types/python.svg",
            Self::Xaml => "icons/file-types/xaml.svg",
            Self::Docker => "icons/file-types/docker.svg",
            Self::Git => "icons/file-types/git.svg",
            Self::Kubernetes => "icons/file-types/kubernetes.svg",
            Self::Powershell => "icons/file-types/powershell.svg",
            Self::Coffee => "icons/file-types/coffee.svg",
            Self::Erlang => "icons/file-types/erlang.svg",
            Self::Markdown => "icons/file-types/markdown.svg",
            Self::Vite => "icons/file-types/vite.svg",
            Self::Bun => "icons/file-types/bun.svg",
            Self::Lua => "icons/file-types/lua.svg",
            Self::Tex => "icons/file-types/tex.svg",
            Self::Nodejs => "icons/file-types/nodejs.svg",
            Self::Kotlin => "icons/file-types/kotlin.svg",
            Self::Elixir => "icons/file-types/elixir.svg",
            Self::Readme => "icons/file-types/readme.svg",
            Self::Image => "icons/file-types/image.svg",
            Self::Prettier => "icons/file-types/prettier.svg",
            Self::Terraform => "icons/file-types/terraform.svg",
            Self::Yarn => "icons/file-types/yarn.svg",
            Self::Ocaml => "icons/file-types/ocaml.svg",
            Self::Dart => "icons/file-types/dart.svg",
            Self::Svelte => "icons/file-types/svelte.svg",
            Self::Julia => "icons/file-types/julia.svg",
            Self::Svg => "icons/file-types/svg.svg",
            Self::Eslint => "icons/file-types/eslint.svg",
            Self::Makefile => "icons/file-types/makefile.svg",
            Self::Css => "icons/file-types/css.svg",
            Self::Php => "icons/file-types/php.svg",
            Self::Typescript => "icons/file-types/typescript.svg",
            Self::Rollup => "icons/file-types/rollup.svg",
            Self::C => "icons/file-types/c.svg",
            Self::Next => "icons/file-types/next.svg",
            Self::Editorconfig => "icons/file-types/editorconfig.svg",
            Self::Pdf => "icons/file-types/pdf.svg",
            Self::Babel => "icons/file-types/babel.svg",
            Self::Proto => "icons/file-types/proto.svg",
            Self::Audio => "icons/file-types/audio.svg",
            Self::Yaml => "icons/file-types/yaml.svg",
            Self::Astro => "icons/file-types/astro.svg",
            Self::Storybook => "icons/file-types/storybook.svg",
            Self::Tailwindcss => "icons/file-types/tailwindcss.svg",
            Self::Nest => "icons/file-types/nest.svg",
            Self::Stylelint => "icons/file-types/stylelint.svg",
            Self::Clojure => "icons/file-types/clojure.svg",
            Self::Video => "icons/file-types/video.svg",
            Self::React => "icons/file-types/react.svg",
            Self::Swift => "icons/file-types/swift.svg",
            Self::Cmake => "icons/file-types/cmake.svg",
            Self::Html => "icons/file-types/html.svg",
            Self::Console => "icons/file-types/console.svg",
            Self::Deno => "icons/file-types/deno.svg",
            Self::Crystal => "icons/file-types/crystal.svg",
            Self::Csharp => "icons/file-types/csharp.svg",
            Self::Graphql => "icons/file-types/graphql.svg",
            Self::Nginx => "icons/file-types/nginx.svg",
            Self::Go => "icons/file-types/go.svg",
            Self::Prisma => "icons/file-types/prisma.svg",
            Self::Haxe => "icons/file-types/haxe.svg",
            Self::Exe => "icons/file-types/exe.svg",
            Self::Webassembly => "icons/file-types/webassembly.svg",
            Self::Gradle => "icons/file-types/gradle.svg",
        }
    }
}

/// Render a typed application icon.
pub fn app_icon(name: IconName, size: f32, color: Hsla) -> Svg {
    name.render(size, color)
}

/// Render a typed provider icon.
pub fn provider_app_icon(provider: &str, size: f32, color: Hsla) -> Svg {
    app_icon(IconName::provider(provider), size, color)
}

#[cfg(test)]
mod tests {
    use super::{FileTypeIcon, IconName, ProviderIcon};

    #[test]
    fn catalog_covers_root_provider_and_file_type_assets() {
        assert_eq!(IconName::Folder.path(), "icons/folder.svg");
        assert_eq!(IconName::TriangleAlert.path(), "icons/triangle-alert.svg");
        assert_eq!(IconName::Pencil.path(), "icons/pencil.svg");
        assert_eq!(IconName::WindowRestore.path(), "icons/window-restore.svg");
        assert_eq!(
            IconName::Provider(ProviderIcon::Gemini).path(),
            "icons/providers/gemini.svg"
        );
        assert_eq!(
            IconName::FileType(FileTypeIcon::Rust).path(),
            "icons/file-types/rust.svg"
        );
    }

    #[test]
    fn provider_names_resolve_to_typed_icons() {
        assert_eq!(
            IconName::provider("claude").path(),
            "icons/provider-claude.svg"
        );
        assert_eq!(
            IconName::provider("google").path(),
            "icons/providers/gemini.svg"
        );
    }
}
