/**
 * Expo config plugin: allow plain-HTTP (cleartext) connections on Android.
 *
 * Expo 57's fetch stack (Nitro Fetch → Cronet) enforces the Android network
 * security config and ignores `android:usesCleartextTraffic`, so a manifest
 * flag alone is not enough. This plugin:
 *
 *   1. writes `res/xml/network_security_config.xml` permitting cleartext,
 *   2. points the application tag at it via `android:networkSecurityConfig`.
 *
 * Both survive every `expo prebuild`, unlike hand-edits to android/.
 *
 * `usesCleartextTraffic` (the legacy flag, still honored by some stacks) is
 * set separately through expo-build-properties in app.json.
 */
const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("node:fs");
const path = require("node:path");

const CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withCleartextNetworkSecurity.js — do not edit by hand.
  Allows plain-HTTP connections to the Console server (dev/LAN, no TLS).
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`;

function withCleartextNetworkSecurity(config) {
  // 1. Write the network security config XML into the Android resources.
  config = withDangerousMod(config, [
    "android",
    async (config) => {
      const xmlDir = path.join(
        config.modRequest.projectRoot,
        "android",
        "app",
        "src",
        "main",
        "res",
        "xml",
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, "network_security_config.xml"), CONFIG_XML);
      return config;
    },
  ]);

  // 2. Point the application tag at the config.
  return withAndroidManifest(config, (config) => {
    const application = config.modResults.manifest.application?.[0];
    if (application) {
      application.$["android:networkSecurityConfig"] = "@xml/network_security_config";
      application.$["android:usesCleartextTraffic"] = "true";
    }
    return config;
  });
}

module.exports = withCleartextNetworkSecurity;
